### PR TITLE
Home Page

### PR DESCRIPTION
**Pull request by courtmcgee2197**
*Please complete the checklist so the group can quickly understand your PR.*

### Category
- [ ] **Feature**
- [ ] **Bug Fix**
- [ ] **Testing**
- [ ] **Documentation**
- [x] **Other**

### Domain
- [x] **Frontend**
- [ ] **Backend**
- [ ] **Both**

### Description
The home page will include the navigation bars and all posts from hubs you are currently a member of

### Related Issue(s)
Reference any relevant issues or PRs to provide context for this PR.

### New Additions
frontend/src/app/home.css  This is for styling of elements on the homepage 

### Modifications
frontend/src/app/page.js Modified to show the posts and navbar although still needs some revision to keep the sidebar
and from overlapping

### New Dependencies
N/A

### Visuals
image

### Usage and Integration
Utilizes the navbar, sidebar, and post-lists components

### Testing
Manual testing by making individual posts in couple different hubs

### Mentions
Tag any group members you want to review this PR, contributed to it, or need to be notified about it.

### CODE REVIEW

**Comment by courtmcgee2197** [comment]
Final Home Page
image

**Comment by leed85** [comment]
looks good, maybe the posts bleed a bit into sidebar? I don't remember the exact px of it.

**Review by leed85 — APPROVED** [review]

**Comment by thecatfour** [comment]
I think it would look better if you listed hubs that the user was in, but this should be enough.

**Review by thecatfour — APPROVED** [review]

**Comment by nnguyen144** [comment]
It would be nice if there was something that indicated the hub for each post.

**Comment by barrioskevin** [comment]
Closes #50

**Pull request merged**
