### PR TITLE
Frontend code for Calendar and Events. Simple backend to store events.

### LINKED ISSUE #3: Calendar
Calendar feature will allow users to add events/schedule and have some customizable features(?)

### PR DESCRIPTION
**Pull request by nnguyen144**
This pull request pertains to the Calendar and events that can be added to them.
Calendar can be accessed on the calendar page at localhost:8000/calendar
I have not implemented the CRUD operations for events in this pull request, so for now events can be managed in [http://localhost:8000/admin/](http://localhost:8000/admin/).
This pull request includes the frontend for the calendar, which displays a calendar for a given month, and that month can be changed using buttons to either go to previous month, go to next month, or jump to current month. Additional ways to change months can be implemented later.
This pull request as of now can display events, and the code for the events can be seen in the backend folder. Events can be retrieved from the API. 
Below is a use case diagram for the calendar.
image

### CODE REVIEW

**Review by nnguyen144 — COMMENTED** [review]
Fixed settings.py and urls.py

**Comment by barrioskevin** [comment]
Hello, I'm going to leave out addressing your current merge conflict from this review. I'm sure you are already aware of the cause and the fix. Instead I will mainly be addressing your new changes you are adding to the code base.

The diagram that you are sharing seems to be a representation of how you want your app to flesh out not how it currently behaves. You have a distinction between hub events, personal events, and non-hub events but I can't really see that reflected in your code. Because we don't yet have a users api there is no concept of a "hub admin" but I can definitely see how you plan on this app working based on what you presented. In the future I would leave "admin" out of any visuals since it's not really a part of our app it's just how we interact with our backend as developers. I would have also loved to see a diagram about your component and the different interactions you make such as switching the months and how the data from the backend gets loaded into the event dates. I appreciate you taking the time to make the visual in order to get a better look into your thought process.

Your backend api for calendar looks good, you added all the things necessary for it to be used from the front end. The structure in which you built your model looks solid too. However, for your `start_time` and `end_time` fields you have them both as `models.TextField()` when I think they can be more accurately represented as `models.DateTimeField()`. You are currently using the date in text format (October 21 2024) for `start_time` and `end_time` and that isn't really a "time" so I suggest a better name. You added in a basic serializer and view for being able to read events and I think that's good this can easily be expanded in the future. Currently you don't have any permissions set so we might want to make it so that only authenticated users are able to see events, this should certainly be the case for adding and deleting events.

As for your frontend changes you introduce typescript into our build. currently our project is configured to run javascript files and only contains the dependencies needed to do so. I noticed that the only places where you actually use type script are in your calendar component where you define the structure of an event and also in some functions where you specify the inputs should be numbers. I personally think this is not a significant usage to add typescript to the project. I was even able to get your calendar working in javascript with a few minor changes (previously mentioned) and it worked well. I'm not saying that we shouldn't use typescript but I'm saying we should be careful with our decision. We are trying to make a MVP by the end of the semester and using typescript can introduce more verbose code that can slow down development. With proper coordination and communication I believe we won't run into much problems sticking with the javascript implementation but of course this should be a group decision. 

That aside, your Calendar component looks really good and I think is the highlight of what you have submitted. The logic you use to handle generating and displaying the calendar and dates seem good enough for it be merged into the main repo so the rest of the group can improve on it over time. cus like right now even if an event is like two days it will only show up on the first day. but like i said it's pretty good and we can always improve over time. 

in MY opinion in order for this PR to be merged
**Must Haves**
- Change the fields for start time and end time to datetime fields.
- Leave out your page where you test the calendar component. Its not necessary for the actual project as we will just be using your calendar component in various different places.
- Talk about how you tested your code specifically your calendar component.  

**Nice To Have**
- Reconsider usage of .ts / .tsx
- only merge your component folder and backend calanden_app folder  
- add permissions to your views.py in order to only allow authenticated users make calls.

**Nit Picks**
- Alot of you code lacks comments, it would be a good idea to write a few for the group to understand and for you when you look back on to remember what the code your wrote is for, hows it's done, and why its useful
- You could add in some basic test in you backend for the view that you have, at this point in time it's not really needed but if you write it now it will be easier for you to be able to write ones in the future quickly.  

To conclude, I think your calendar component looks great and will serve it's purpose in our project well. With some minor changes to your current PR I think this would be a clean merge that will help us make great progress in developing our app.

**Comment by nnguyen144** [comment]
>cus like right now even if an event is like two days it will only show up on the first day. but like i said it's pretty good and we can always improve over time.

In my opinion I think having it as it is is fine as on the Canvas Calendar, which I am taking much inspiration for my design on, it currently doesn't have an option to have the event expand to multiple days off of one create.
> 
> in MY opinion in order for this PR to be merged **Must Haves**
> 
> * Change the fields for start time and end time to datetime fields.

I fixed this. Thank you for the suggestion.

> * Leave out your page where you test the calendar component. Its not necessary for the actual project as we will just be using your calendar component in various different places.

For people to view and test the calendar functionality, I think its best to leave as it is for now, but later on it can definitely be implemented as just a component rather than a page + component.

> * Talk about how you tested your code specifically your calendar component.
> 

I manually tested the functionality of my calendar by interacting with the calendar and verifying numerous things, such as:
- the creation of an event with a specific date and checking that the event is on the correct date on the calendar
- checking for edge cases, such as events that aren't in the current month but are on the calendar grid (due to being on the first days of the next month or the last days of the previous month) and checked to see if they show up
- checked the layout of a given month and compared it to what it should look like

> **Nice To Have**
> 
> * Reconsider usage of .ts / .tsx

I fixed this. Thank you for the suggestion.

> * only merge your component folder and backend calanden_app folder

See the answer above starting with "For people to view..."

> * add permissions to your views.py in order to only allow authenticated users make calls.

I will definitely implement that later on when I work on the CRUD operations, but for now this PR is mostly for the frontend for the calendar and events, and just enough backend for events to show up properly.

> **Nit Picks**
> 
> * Alot of you code lacks comments, it would be a good idea to write a few for the group to understand and for you when you look back on to remember what the code your wrote is for, hows it's done, and why its useful

I added comments to Calendar.js that should clarify each part of it.

> * You could add in some basic test in you backend for the view that you have, at this point in time it's not really needed but if you write it now it will be easier for you to be able to write ones in the future quickly.

See the answer above starting with "I will definitely implement that..."

I was having conflicts with the settings.py and urls.py files in backend/rebel_hubs, so I restored them and they no longer include my calendar_app inclusions, which is something that will need to be fixed later on.

Is there anything else that needs to be done before this PR can be merged?

**Comment by barrioskevin** [comment]
Hi, I took a look at your fork and noticed in your master branch that you don't even have the current version of our main repo. this is most likely why you are running into issues with your pull request. (still has conflicts atm)

The changes you made to your event model look better since we are now working with dates instead of text fields, It's just that you have a field for date which is nice but then your `start_time` and `end_time` are both also dates (datetimes). If you wish to separate the dates and the times then we would be better off making `start_time` and `end_time` both `model.TimeField()`'s. Where they can only be assigned a time and not a date. This is similar to the way Canvas handles the date, start, and end. 

Also, the way you have it set up now, I can make an event that has a different date then the date field and I can also make the end time for an event be a date that comes before the start time (see below). There is no logic to handle this in your code, of course we can try to force a correct input on the frontend but I don't think that would be the best approach we should make sure our code can only behave as expected.
image

Furthermore I think the switch from text format to date format altered the logic in your component. When I create an event for a certain date lets say 2024-10-24 the event shows up on your calendar under the date 2024-10-23. I created various different events in order to test this and they all seem to appear a day before on your component. You say yourself that you manually tested it so I'm not sure if it slipped passed you or something but this really showcases the importance of writing unit tests. 

I am happy to see that you decided to make your component a .js file. That makes this merge all the more simpler. For this pull request you currently have 23 files changed. 
image
I think a lot of these file changes/additions are unnecessary for your pull request I recommend only uploading the following
- backend/calendar_app/*
- frontend/components/Calendar/*  

The other file changes seem to be related to when you tried adding in typescript, which is no longer need, and from when you were trying to add in your urls and app name into settings. The calendar page isn't really needed at this point in time since if someone wanted to see you calendar they can easily just import it into a testing page that they have in their own fork. If you really want to add in your calendar page then I would change the extension from .tsx to just .js since our project is configured to build and run js files. 

Overall I think your calendar component looks promising and I wish you luck in resolving the PR. Thank you for your time!

**Comment by nnguyen144** [comment]
I'll be making a new PR with some corrections.

**Pull request closed without merging**
