### PR TITLE
Backend for Make Post with Likes and Dislike Feature

### PR DESCRIPTION
**Pull request by misherwa**
This pull request is for the Make Post and Like/Dislike features for issue #2 

The Post feature is for the structure of a Post, with fields like author, title, message, timestamp, hub, likePost, and dislikePost. There is a Post Serializer that is used to convert data into JSON format for better usage with the API and front end.

For the Post feature, the front end would use submitPost() to send the data to the API. The fetchPosts() will be used to get a list of posts. The API takes the POST request and it gets processed by the CreatePost class in views.py. This holds the data from a user who is creating the post, which is the title, message, and hub category. Also, in the view.py file is the PostList class that handles the GET request. It calls the Post.objects.all() query. All the data will be stored in the Post Table database.

This is the UML design requirements for the Comment/Post feature, but the main focus is the backend of the Post.
q2

For the Like/Dislike feature, the front end will use buttons assigned to likes and dislikes. The API will handle the request when another user likes or dislikes a post. This will be handled by the likePost() and dislikePost() in the backend. There will be an update to the Post table that stores the number of likes and dislikes from the Post.

This is the UML design requirements  for the Like/Dislike feature
Likes Dislikes

Here is a view of the coverage results
coverage

### CODE REVIEW

**Comment by barrioskevin** [comment]
Hello, This is a nice Post api structure that closely follows our original idea presented in our design document. 

Before this gets submitted I think we should remove the commits to 'testhubs' from your PR. It will make the commits in your PR closely reflect the actual functionality being implemented.

If you can provide more explanation to what the 'create' method in the PostSerializer class is doing that would be great, but it looks like it's dealing with the User api that hasn't yet been implemented.

In the future we would want the Posts to reference a hub as a foreign key similarly to how you did it with 'author'. This would ensure that a Post is properly assigned to a hub. This can be added once the Hub api is created but it will affect your test cases.

In views.py we should also be adding in methods for retrieving a **single** post since we would need it in the front end when we display a more detailed view of a post. You can also try adding in methods for deleting a post.

You do have fields for upvotes and downvotes however there is no function that actually handles liking or disliking a post as mentioned in your PR _"...This will be handled by the likePost() and dislikePost() in the backend. There will be an update to the Post table that stores the number of likes and dislikes from the Post."_ Additionally, the fields are called likePost and dislikePost when they should be named something like numberOfLikes or numberOfDislikes or simply just likes and dislikes so it's more clear that they reflect an integer count representing the upvotes/downvotes.

As far as the comments go, a lot of them lack a better explanation of usage/reasoning. Most of them can easily been derived from looking at the code. I would suggest more meaningful comments that can help us as developers better understand how the code works and more importantly how to use it. 

In MY opinion for this PR to be merged
**Must Haves**
- remove commits involving 'testhubs' from the PR.
- Add in methods for liking and disliking in the backend.

**Nice To Have**
- Hubs being referenced by foreign key, updated test case to match
- Extra views in views.py for doing a GET on a single post and DELETE a post
- Rename the likePost dislikePost fields

**Nit-Picks:**
- Comments used throughout your files could be more meaningful and you should remove unnecessary ones. (they seem generated)
- You also import HttpResponse in views.py but im not sure that you ever use it.

Overall you did a really nice job hooking up you Post api application to our django backend. The urls are handled properly and you made sure to add the new models to the Admin panel. I also like how you added in tests into your app maybe this could be a mandatory thing going forward after the rest of the group gets a better understanding of how it works. To conclude, I think if you make those few adjustments this will be a clean merge into our project!

**Comment by misherwa** [comment]
Thanks for the detailed input Kevin. 

I provided a better explanation of the  'create' method in the PostSerializer class, here's what it looks like:
Create method

 For your must haves, I removed all the commits from the "testhubs" that I made.  I made the methods for likes and dislikes which look like this, but I named the classes "likePost" and "dislikePost" in the view.py if that's ok:
Methods


For your Nice to Have, I just made a note to reference so I can make changes after the foreign key is made.  I renamed the "likePost" and "dislikePost" to "likes" and "dislikes", as you mentioned that these names are much simpler.  You can see the name changes in the model .py and serializers.py files.  

Here's what the Extra views in views.py for doing a GET on a single post and DELETE a post look like:
Extra Views



For the nitpicks, I removed the comments that seemed unnecessary and the HttpResponse in views.py.

I'm just going to try to make sure the test coverage is 100 percent, so I'll let you know when I am done with that. But If there are any issues you find or comments you have, could you please let me know? thanks!

**Comment by misherwa** [comment]
I finished the test coverage. It used to be 77% for the coverage since I changed models.py and views.py, and you can see some of the changes in the comment above. 

So, I needed to add test cases for liking and disliking a post, interacting with an invalid post, and making a post without a title. 

Here's an example of the test cases you can find in tests.py. In this case, there exists a missing field in the post, which is  the title:
testcase


This is what the test coverage looks like now:
coverage

**Comment by barrioskevin** [comment]
Wow this looks awesome, I wouldn't worry too much about the testing at this stage in development. I think it's good that you did write them though, it helps us know what to expect. I can still see the changes involving 'testhubs' but honestly it doesn't even matter since it will be deleted eventually. The views you added for like, dislike, and detailed view look solid the method names aren't all that important but the new names for the fields in the Post model are much more clean (likes and dislikes). Again, this looks really good and if it was up to me I would merge right now. But I think we should have at least one other group member take a look at this and share their thoughts.

**Comment by misherwa** [comment]
Thanks, and for the "testhubs" I thought I removed all the things I added except for the migrations folder. So If you're talking about the migrations folder, then I can delete it and update the PR?

**Comment by barrioskevin** [comment]
yeah you're right you did remove everything you added. the test hubs folder still shows up under "files changed" that's why i said something. again, not that important actually but you can do what you like

**Comment by thecatfour** [comment]
This will probably be a problem that we can address in the future, but I have concerns with the PostList view. It seems to get all of the posts in the database and return those. Depending on the amount of posts, this may take excessive memory. Of course, since there aren't many posts, this shouldn't be a problem right now. I think we could just make a new issue regarding this and fix it later. 

image

Other than this future issue, I believe this can be merged.

**Pull request merged**
