### PR TITLE
Backend User Creation/Authentication Api

### PR DESCRIPTION
**Pull request by courtmcgee2197**
Setup up the backend user api  as well as added to requirements.txt

### CODE REVIEW

**Comment by courtmcgee2197** [comment]
The User_Api takes in a username, password, and email address. Using the serializer class it creates a json representation in the database. The views.py will allow you manually add users and the admin.py will allow you to view user creation.

**Comment by barrioskevin** [comment]
Hello, The user creation and authentication api you submitted looks promising and I think it's a good start for setting things up. 

The changes that you made all seem necessary to getting the users authentication working. I am a little concerned about the requirements.txt file in our backend folder though. Are you running this project in a virtual environment? If not I suggest that you do, especially if you are going to introduce new libraries/dependencies. Then you can easily regenerate the requirements.txt file by running 'pip freeze > requirements.txt' in the backend folder from your virtual env.

In our main projects 'settings.py' you also are commenting out the old cors allowed origins and doing cors allowed all origins = true. If this was for testing purposes all you have to do is add in your front end's server link (prolly  just adjusted port) to the existing array. For example if next js is running on a different port like 2000 or something just add in the url. I think this is good practice for security? But I could be wrong so you can feel free to let me know.

Also, we are trying to keep a conventional naming scheme for our api endpoints in the backend. when adding in new url patters in the main projects 'urls.py' we are going to add the api/ prefix here. your User api app's 'urls.py' will have your app name followed by some name that helps us see what it does. So in your case rebel_hubs/urls.py would look like
```python
urlpatterns = [  
   ....old urls....,
   path('api/', include('User_Api.urls')),
] 
``` 

And your User_Api/urls.py would look like 
```python
urlpatterns = [
   path('users/create', CreateUserView.asView(), name='create-user')
]
```
I believe you can make the path anything so we don't need to have User_Api/... in the endpoint since it will be tedious calling this from front end. You can leave it called register if you like, but if we use create instead it fall closely to how we will be creating hubs, posts, comments, and more in the future. If we follow the convention it will make easier to work with imo.

I notice that your app doesn't include any models. Is this so we use Django default User model? That seems like a good idea but how do you plan on associating fields that are related to our app with the user? such as joined hubs, owned hubs, posts, likedposts, calander events, friends, dms, etc. 

You are also adding in this Simple JWT library and set some things up in the main app's settings.py. Can you explain more about what this does? You kind of left it out in your original description. I have an idea of what it's for but I'm having a hard time seeing it being used. (same for permissions group).

I think we should add in some more to the initial submission for User Api. This is a very import app that will be the backbone of the rest of our api's since most will rely on valid users. Do you mind adding in more than just create, such as update (i.e. changed user name) and login.
adding in update with just a basic user name update will be good enough for us to eventually be able to make updates like update a user's likes or update a user's followed hubs or what not. 
adding in a login will help the rest of us seeing how the JWT tokens work, you don't need to do anything extreme you can just make a something simple where we can see the authenticated user in action. Then we will know what is needed to make endpoints that require a valid user.

There's no tests written in your tests.py and you don't mention any testing in your original post but from what I have read and from what you shared before with the first version working im sure everything works well. But if you want to do testing on your own try to test out your endpoints since this is what the front end will be using, not the admin panel. 

in MY opinion for this pull request to be merged
**Must Do:**
- Add in new urls for updating a user and add url for demonstrating your JWT implementation

**Nice To Have:**
- Make your urls follow the convention of 'backendURL/api/users/' 
- Try to add some comments in 'rebel_hubs/settings.py' to help explain the changes and additions you made. 

**Nit Picks:**
- Explain more (either in your post or in code comments) about how you tested the api and how it's used.
- Making the requirements.txt include version numbers and only the dependencies used in the project (look at virtual envs).
- Add in endpoints for deleting user, or retrieving user information by id (this can be added later so not really important).

Overall this looks like a solid setup for incorporating users and authentication into our app. I hope with some few adjustments that the logic becomes more clear and we can eventually merge this in. Once the user api gets merged into our app it will kick off a lot of things and we will be able to advance and build out the rest of our application quickly. I hope you can see the importance of your api. Thank you for your time!

**Comment by misherwa** [comment]
Hey Courtney, Kevin first mentioned a merge conflict on our group Discord channel. It might be a simple fix. It seems that both files have line conflict issues, so I'll try to go step by step. If it looks confusing, please just look at my second to last image about line 43 being blank, which is how your code might have to look to fix the conflict issue for the settings.py file. The last image is about the urls.py file.

Starting with conflict in settings.py in the rebel_hubs folder, this is what the conflict looks like:
q

Here's what the same setting.py file looks like after the #8 PR:
q2

And this is what the setting.py fil for your #9 PR looks like: 
q3

I think it's a line issue, so you would have to add your 'User_Api' to a different line.
For example, I added it to line 44:
q4


Note: I think you also deleted line 14, so everything got shifted upwards.
testcase


So line 43 should be blank and this is what your code should look like:
Methods

Next, to fix the conflict issue with the urls.py file, I think you would have to just move your " path('',include('User_Api.urls'))," to a different line. It looks to me that you would have to put it in line 25 based on this:
coverage

**Comment by misherwa** [comment]
Sorry Courtney, there seems to be some new line conflicts in the settings.py and urls.py files. This is due to the code being updated from "Extension of PR#12." from the PR #16. 

As of PR #16, this is what the urls.py file looks like:
urls

And this is what the settings.py file looks like:
settings


I suggest you should update these two files closer to your last commit, rather than having to update it every time a new PR get's accepted and it adds to the setting.py or urls.py. So for now, you can focus on adding commits for what Kevin suggested above.

**Review by leed85 — APPROVED** [review]

**Comment by thecatfour** [comment]
PR #18 implements these changes plus a few updates in the backend of user creation, so I think it is best to close this PR for now.

**Pull request closed without merging**
