### PR TITLE
Backend comments

### PR DESCRIPTION
**Pull request by misherwa**
*Please complete the checklist so the group can quickly understand your PR.*

### Category
- [x] **Feature**
- [ ] **Bug Fix**
- [ ] **Testing**
- [ ] **Documentation**
- [ ] **Other**

### Domain
- [ ] **Frontend**
- [x] **Backend**
- [ ] **Both**

### Description
This pull request is for the Make Comments under posts and allows for comments to be liked or disliked. It introduces a new folder called "Comments". 

### Related Issue(s)
No related issues.

### New Additions
- __init__.py: Define and initialize packages
- admin.py: Used to display the models.
- apps.py: Configuration
- models.py: Design of the database structure for comments.
- serializers.py: Converting datatypes, and used to validate data for API calls and requests,
- tests.py: Placeholder for test
- urls.py: Used for endpoints, some involving "Posts", such as "posts/<int:post_id>/comments/".
- views.py: Logic to return or request from responses.

### Modifications
backend/rebel_hub/urls.py: Added comments URL back into the file, so that it can be used in admin test pages.

### New Dependencies
No new Dependencies

### Visuals
image
Attempting to follow the backend of this first visual for the Make Comments. The backend requires the PostID for what comment is associated with what post. It's named post_id and is used when creating new comments and assigning them to the post. The CommentID or "comment_id" in the code is used for getting and updating the comments, and this also includes the likes (upvotes) and dislikes (downvotes). The content refers to the message from the comment. Timestamps are used to display the comments in order from the newest on the top, and the oldest at the bottom. It is also possible to order it from the most likes being at the top.

### Architecture of Your Changes
The main architecture of these changes is to include comments to posts from PR #30. Whenever a post is created, users can comment under the posts. Comments can be deleted by the correct authorized member, otherwise, it will be shown from either the most likes or most recent comment at the top. Any likes or dislikes the comment receives should be updated by an increment of one. If a user has liked a comment and then chooses to dislike the comment, it should work by decreasing the like by one and incrementing the dislikes by one or vice versa.

### Usage and Integration
Comments should be found under posts and can be created multiple times by anyone. However, only a moderator or the user of the comment should be able to delete it.

When using CommentList or CommentCreate, posts should be linked to the URL such as "posts/<int:post_id>/comments/" when getting the list of comments or "posts/<int:post_id>/comments/create/" when creating a comment.

### Testing
Note: No test cases as of now. The test cases will be done in a different PR, and the number will be linked to this when it is done.

### Mentions
@imawful and @thecatfour need to be notified about this PR.

### CODE REVIEW

**Comment by nnguyen144** [comment]
Hello misherwa,

while I believe that you have written a good backbone for comments, as of right now, it appears that comments are not linked to each other and are only linked to a post. Replies are a crucial part of comments as they allow users to see related comments in succession.

To implement replies, I believe you could make a ForeignKey which points to a reply of the current comment. Thus, when you are printing the comments on the browser, you could recursively use the foreign keys to print out comments while also having some signifier that the comment is a reply. This can be done in many ways, including indenting replies.

If replies are not part of the vision that we have for our project, then your PR can be merged. But I believe that replies would be useful to include.

- Nathan Nguyen

**Comment by thecatfour** [comment]
I believe Nathan's suggestion would be very useful for displaying comments. However, since comments can be directly created on posts, there needs to be a way for the ForeignKey to show that it is not a reply to an existing comment. Maybe adding null=True and blank=True to the ForeignKey constraints could solve this.

**Comment by misherwa** [comment]
Thank you for the insight Nathan Leslie,

I think replies would also be useful to include, so I'll just add the basics. 

I added a new field called "comment_reply", which like what you said, uses a ForieginKey and points to a reply to a comment. For now, I'll try to have it so that you would get a list of the replies from a comment by hitting a button from the front end called something like "Replies". I updated the models.py so it includes this:
q

I updated my views.py to include "CommentReplyCreate" for creating a reply on a comment, and "CommentReplyList" to list all replies from a selected comment.

**Comment by thecatfour** [comment]
I think the CI test failed because your repository doesn't have the pytest.ini file.

**Comment by misherwa** [comment]
> I think the CI test failed because your repository doesn't have the pytest.ini file.

Thanks, it just requires 2 approvals now

**Review by thecatfour — APPROVED** [review]
Everything seems to be in order now. The comment reply field is in the migration, so it should work fine. It also passes the CI test.

**Review by leed85 — APPROVED** [review]

**Pull request merged**
