### PR TITLE
Profile_V1

### PR DESCRIPTION
**Pull request by leed85**
Please complete the checklist so the group can quickly understand your PR.

Category
 X Feature
 Bug Fix
 Testing
 Documentation
 Other

Domain
 Frontend
 Backend
 X Both

Description
First part of profile:

Created new profile model that includes a name (separate from username), bio, pfp

Created edit profile page to update profile name, pfp, bio

Made update posts to fetch all of user's post count
Made update to make hubs count actually match amount of hubs

Updated Navbar to have profile information

Related Issue(s)
https://github.com/UNLV-CS472-672/2024-F-GROUP3-RebelHub/issues/49

New Additions
In Description

Modifications
        modified:   .gitignore
        modified:   backend/Posts/serializers.py
        modified:   backend/Posts/urls.py
        modified:   backend/Posts/views.py
        new file:   backend/Profile/__init__.py
        new file:   backend/Profile/admin.py
        new file:   backend/Profile/apps.py
        new file:   backend/Profile/migrations/0001_initial.py
        new file:   backend/Profile/migrations/0002_remove_profile_picture_profile_name_profile_pfp_and_more.py
        new file:   backend/Profile/migrations/__init__.py
        new file:   backend/Profile/models.py
        new file:   backend/Profile/serializers.py
        new file:   backend/Profile/signals.py
        new file:   backend/Profile/tests.py
        new file:   backend/Profile/urls.py
        new file:   backend/Profile/views.py
        new file:   backend/media/defaultpfp.png
        modified:   backend/rebel_hubs/settings.py
        modified:   backend/rebel_hubs/urls.py
        modified:   frontend/src/app/page.js
        new file:   frontend/src/app/profile/editprofile/page.js
        new file:   frontend/src/app/profile/editprofile/profileedit.css
        modified:   frontend/src/app/profile/page.js
        modified:   frontend/src/app/profile/profile.css
        modified:   frontend/src/components/navbar/AccountButton.js
        deleted:    frontend/src/components/sidebar.js
        renamed:    frontend/src/components/sidebar.css -> frontend/src/components/sidebar/sidebar.css
        new file:   frontend/src/components/sidebar/sidebar.js
        modified:   frontend/src/utils/url-segments.ts

New Dependencies
n/a

Visuals
editprofilev1
profilev1

Architecture of Your Changes
n/a

Usage and Integration
Profile now has the following info: 
preferred name
bio
pfp
hub_count

it is connected 1 to 1 with user model

Testing
n/a

### CODE REVIEW

**Comment by leed85** [comment]
This is v1 - I still am implementing displaying all photos/posts on user profile page and visiting others profile page - hope to be pull requests in a day

**Comment by misherwa** [comment]
Hey Daniel, I recommend doing your PRs as a draft going forward. I believe that drafts are recommended according to Design Portfolio Evaluations. But drafts also help with showing us your progress, and if you need any help or suggestions, we can check your PR draft. Once you're done with your draft, you can go ahead and submit it for review from your PR Draft page, the button should be around the bottom right.

For example, for your V2 of the profile, you should start it as a draft PR. This is done by going into your V2 branch and doing a small commit. Then instead of doing the "Create Pull Request", you select the section option which includes the word "Draft". 

Here's a link for PR drafts if you need more details: https://github.blog/news-insights/product-news/introducing-draft-pull-requests/ 

I'd also recommend using a design diagram. You could do it on either this version or the next version you plan to implement later. The design document recommends using https://mermaid.js.org/ but you could also use another UML design diagram website that you like.

Regarding your CI workflow error, I removed the changes you made in the rebel_hubs settings.py file. So I removed, 'Pictures' and 'Profile' from installed apps and your changes that start on line 161. It still results in a failure, but it seems that some of your issues are coming from what you added in the settings.py file:

cur

**Comment by misherwa** [comment]
> This is v1 - I still am implementing displaying all photos/posts on user profile page and visiting others profile page - hope to be pull requests in a day

Sorry Daniel, I just wanted some clarification for PR #78 (Version 1). I'm getting confused on what "Pictures" is supposed to be for. Like in rebel_hub folder and inside the settings.py you have "Pictures" in the INSTALLED APPS. However, I believe you would need to create a "Pictures" folder in the backend, like how you did "Profile".

So were you planning on adding "Pictures" to this Version 1, or is it supposed to be for your Version 2? 

If you are planning on adding it for your version 2, it looks like you need it remove or comment out all modifications that include your "Pictures" feature. 

For example, looking at this error from going to the backend and running pytest:

cur

If you remove or comment out "Pictures" as seen in line 49 below. It will run pytest but there will be some errors.
q4

**Comment by leed85** [comment]
> > This is v1 - I still am implementing displaying all photos/posts on user profile page and visiting others profile page - hope to be pull requests in a day
> 
> Sorry Daniel, I just wanted some clarification for PR #78 (Version 1). I'm getting confused on what "Pictures" is supposed to be for. Like in rebel_hub folder and inside the settings.py you have "Pictures" in the INSTALLED APPS. However, I believe you would need to create a "Pictures" folder in the backend, like how you did "Profile".
> 
> So were you planning on adding "Pictures" to this Version 1, or is it supposed to be for your Version 2?
> 
> If you are planning on adding it for your version 2, it looks like you need it remove or comment out all modifications that include your "Pictures" feature.
> 
> For example, looking at this error from going to the backend and running pytest:
> 
> cur
> 
> If you remove or comment out "Pictures" as seen in line 49 below. It will run pytest but there will be some errors. q4

yea its part of v2, its for posts so that I can link posts with pictures while also keeping it separate to posts for future scalability and easier modification if needed

**Comment by misherwa** [comment]
Oh, thanks for explaining. So were you planning on commenting out "Pictures"?

**Comment by leed85** [comment]
weird bug, if you log in and instantly goto profile page, the layout gets messed up, need to refresh after logging in to make it work

**Comment by leed85** [comment]
> Oh, thanks for explaining. So were you planning on commenting out "Pictures"?

yea, forgot to do that, thanks

**Comment by leed85** [comment]
I am going to take down this pull request as I am almost done with V2, I tried testing this and it looks like it wont run without the Picutures app

**Comment by misherwa** [comment]
> I am going to take down this pull request as I am almost done with V2, I tried testing this and it looks like it wont run without the Picutures app

Gotcha, you should probably do your V2 PR as a draft

**Pull request closed without merging**
