### PR TITLE
Language Filter

### PR DESCRIPTION
**Pull request by misherwa**
*Please complete the checklist so the group can quickly understand your PR.*

### Category
- [x] **Feature**
- [ ] **Bug Fix**
- [ ] **Testing**
- [ ] **Documentation**
- [ ] **Other**

### Domain
- [ ] **Frontend**
- [ ] **Backend**
- [x] **Both**

### Description
Providing a language filter to any messages, comments, descriptions, names, bio, and titles. This filter stops inappropriate words from being used in places like for the profile, comments, posts, and hubs.

### Related Issue(s)
#87 "Language Filter Needed"

### New Additions
-Comment/filter.py (Holds the inappropriate_language_filter function)
- Posts/filter.py (Holds the inappropriate_language_filter function)
- Hubs/filter.py (Holds the inappropriate_language_filter function)

### Modifications
- Comment/serializers.py (Validating that appropriate language is being used in comments and replies)
-  Comment/test.py (Checking test cases)
- Posts/serializers.py (Validating that appropriate language is being used in the post title and message)
- Hubs/serializers.py (Validating that appropriate language is being used in Hub name and description)
- Profile /serializers.py (Validating that appropriate language is being used in user profile bio and name)

### New Dependencies
None

### Visuals

Here is an example of a set of you can do, with the inappropriate word being "crap":

image
q2

 Above are two images that give two separate errors. One if you use bad words in the bio, and the other is if it's in the name. You can also try doing this with, posts, hubs, and comments.

image
Example of using "crap" and getting an error message in comments.

image
Here's what Hubs looks like with an error message by adding "Crappy", it also works if you just do "crap".

### Architecture of Your Changes
Users who interact with Posts, Messages, their profile, and Hubs, won't be able to use inappropriate language due to an added validation check in the serializer.py files

No other modifications to the existing system, only improvements to test coverage results and error handling.

### Usage and Integration
This interacts with the serializer to introduce a layer of validation to check for inappropriate words in specific fields like name, title, message, and description.

### Testing
Testing was done in the front end by using inappropriate words in the specific fields mentioned above. I tried using "crap" and even changing the way certain letters are capitalized such as doing "cRaP". I also tried combining other words or letters around the word, such as "FeelingLikeCrapToday". All these word combinations and trials gave errors because an inappropriate word was used, which is good.

### Mentions
N/A

### CODE REVIEW

**Comment by leed85** [comment]
I think this looks good, I think we can in the future add a section in the database or a json file with all disallowed words in the future as it grows

**Review by leed85 — APPROVED** [review]

**Comment by courtmcgee2197** [comment]
Overall looks good.  Currently the list of disallowed words is only limited to common curse words. Obviously over time we would add more to the list of disallowed words to also cover slurs of any  kind. Minor nitpick the message you receive when trying to use the disallowed words is a bit close. 
image
Either way however it looks safe to merge.

**Comment by misherwa** [comment]
> I think this looks good, I think we can in the future add a section in the database or a json file with all disallowed words in the future as it grows

Thanks,

I believe you're right and this should be considered when actually developing and deploying this platform

**Review by courtmcgee2197 — APPROVED** [review]

**Comment by misherwa** [comment]
> Overall looks good. Currently the list of disallowed words is only limited to common curse words. Obviously over time we would add more to the list of disallowed words to also cover slurs of any kind. Minor nitpick the message you receive when trying to use the disallowed words is a bit close. image Either way however it looks safe to merge.

Yeah, I think you're right about the spacing issue with the error message. 

Here's an update: 
image

**Pull request merged**
