### PR TITLE
Comment components

### PR DESCRIPTION
**Pull request by thecatfour**
### Category
- [X] **Feature**
- [ ] **Bug Fix**
- [ ] **Testing**
- [ ] **Documentation**
- [ ] **Other**

### Domain
- [ ] **Frontend**
- [ ] **Backend**
- [X] **Both**

### Description
This PR modifies some of the backend Comments files to better fit frontend functionality. It also implements the components necessary to display a post's comment and replies.

Several of the files in this PR are the same as some changes from #66, so this PR should not be merged before #66.

### Related Issue(s)
This PR addresses parts of #53.
This PR also updates:

- Modals so that they follow the user's screen.
- The CreateInput component so it can be submitted using the enter key.

### New Additions

**RecursiveCommentList.tsx:** The main component from this PR that displays all the comments on a post.

- **comments/buttons/CreateCommentButton.tsx:** Simple button to help with the placeholder create comment component.
- **comments/buttons/DeleteCommentButton.tsx:** On click, it shows a modal to delete a specific comment.
- **comments/buttons/ShowMoreButton.tsx:** This "button" is a div that is used to help display an increasing amount of comments.
- **comments/forms/CreateCommentForm.tsx:** Used to create a comment and reply.
- **comments/CreateComment.tsx:** The placeholder comment that is displayed when making a comment.
- **comments/RecursiveComment.tsx:** The component that displays a comment and its replies.
- **comments/SingleComment.tsx:** The component that displays a single comment or reply.

### Modifications

- **posts/post-summary-detailed.tsx:** Modified to display a RecursiveCommentList and CreateComment to allow the user to engage with the comments of a post.
- **backend/Comments/views.py:** Modified to be similar to the PostDelete view.

### New Dependencies
No new dependencies.

### Visuals
Here is a gif of how the comments work:

ezgif-3-5a94b636e7

Here is a gif of how the ShowMoreButton works with the comments:

ezgif-7-fa822069a1

Here is a use case diagram of the main idea of how the components interact with each other:

comments use case drawio

Here is a basic visual of how the comments are structured within each other:

comments structure drawio (1)

### Architecture of Your Changes

In order to distinguish comments and replies. I created three main components to render comments. 

The SingleComment component is used to render a single comment/reply. It also controls the likes/dislikes of the comment, the CreateComment component to create a reply to a comment, and the delete button component. In order to make sure comments and replies are rendered correctly, the SingleComment communicates with its parent component, a RecursiveComment.

The RecursiveComment component is used to render a SingleComment component and create new RecursiveComment components to render the replies to the SingleComment component. It creates several functions to maintain its comment list state. Basically, it renders the comment, and then it attempts to render any replies to the comment.

The RecursiveCommentList component is used to initialize a list of RecursiveComments. It can be told to only render a specific amount of recursive comments, but it only counts the comments that are directly on the post. It also includes a CreateComment component in case a user wants to comment directly on a post.

Since comments are tied to a post, currently only the PostSummaryDetailed component uses the RecursiveCommentList. 

### Usage and Integration
The RecursiveCommentList is the main component being added in this PR, but RecursiveComment can also be used to show a thread or larger reply chain. Since they are tied to a post, it may not be a good idea to separate comments from the detailed post they are displayed on.

### Testing
Testing was done using the posts page we have on the frontend.

Currently, replies do not save likes/dislikes. This is intentionally set up in the backend, so depending on whether or not we want to includes likes and dislikes for replies, the like/dislike buttons can be hidden from replies in the future.

### Mentions
@nnguyen144, @imawful, and @misherwa may have use for these components as they are working on files that involve posts, and by extension, comments.

### CODE REVIEW

**Comment by misherwa** [comment]
Hey Leslie, the comment components is looking pretty good from your examples. 

I tried testing it on my end, and I created some comments under the username"aarush":
w


I then switched accounts by going back to the login, and logging in with an account under "aarushm". I went back to the same Post, and the username from the comments got changed from "aarush" to "aarushm", and it looks like this:
q4

If you refresh the page, for about a second all the usernames of the comments are "UNLV Student", and then they get fixed to an actual username:  
q2

I also made another user called "billy" and added the username to the comment reply. You can see that it say's the names "aarushm" or "billy" in the reply and that's what the username should appear as when you look at who commented. But it just defaults to "aarush" which is the current user I am logged in as. I hope this makes it a little less confusing:
cur

And here's a view of the backend:


I think the issue might be that it is pulling the name from the user viewing the comments, rather than the user who made the comment.

**Comment by thecatfour** [comment]
The problem was with AccountButton.js, which I had to refactor. The component can now take in a username prop and a noBackground prop, both of which are optional. If a username is passed, then it will determine if the username is an id or a string and make calls to the backend if necessary. The noBackground is just used to make the name more clean on the comment component.

image

The AccountButton also redirects to the user's profile.

**Review by misherwa — APPROVED** [review]

**Comment by barrioskevin** [comment]
The account button does redirect to the user, however when in the nav bar it also redirects to the user's page under `/profile/user/` instead of just `/profile/` this means that when you click on your own user from the nav bar you won't be able to see the edit profile option. I don't think this is an issue from your changes, it's more the fact how the profile page was set up but if you can make the account button redirect to `/profile/` if it's your own account that would be nice. 

And also for comments maybe it would be a good idea to indicate the original author. for example if an author makes a post and then later on comments in a thread under that post we can maybe highlight the name to show that it's the original author. Maybe even the same for hub moderators? But it might not be necessary just a "nice to have". 

Also since we don't have any timestamps or anything on the views of comments, it might be a better idea to change the order of the comments. Most sites usually have the newest comments last on the list and if there is a lot we hit like a show more where we see the rest of the comments and typically the first comments are the ones that appear right under the initial post. 

Other than that I am not really getting any technical issues with your changes so things seems to be working fine, I appreciate all your work!

**Comment by barrioskevin** [comment]
also is the [Edit] just a placeholder? kind of confusing since it makes it seem like the comment might have been an edit

**Comment by thecatfour** [comment]
The AccountButton now correctly sends the user to their own profile when clicked.

I modified the comment structure to show if a commentor is the author is the post.

image

Comments are also ordered oldest first. If a user creates a new reply or comment, it will be displayed at the top on their client until they reload the page. Timestamps are not displayed, but they could be shown in the same row as the (Post Author) part.

I removed the "Edit" placeholder as there may not be time to add edit comments feature.

**Comment by barrioskevin** [comment]
The account button works as expected now.

The ordering changes you made are great! I would have just preferred that we prioritize viewing the newest things first that way we don't have to press view more to see the latest replies, but I understand that might be tricky having to differentiate from posts, comments, and replies. In the end it's just a view change so it shouldn't be much trouble if we want to edit it in the future.
(im speaking more about a comment with a lot of replies not necissarly the posts, sorry if this is confusing i was using youtube comments as a reference. I think the way things are set up at the moment is fine)

the component looks a lot cleaner without the edit tag.

**Review by barrioskevin — APPROVED** [review]

**Pull request merged**
