### PR TITLE
Frontend DM

### PR DESCRIPTION
**Pull request by leed85**
Please complete the checklist so the group can quickly understand your PR.

Category

- [x] Feature
- [ ]  Bug Fix
- [ ]  Testing
- [ ]  Documentation
- [ ]  Other

Domain

- [x] Frontend
- [ ]  Backend
- [ ]  Both

Description
Frontend for DM/PM features

Related Issue(s)
n/a

New Additions
messages frontend

Modifications

New Dependencies

Visuals
image

Architecture of Your Changes

Usage and Integration

Testing

Testing Approach: Mention whether you applied unit, integration, or end-to-end tests.

Mentions

### CODE REVIEW

**Comment by misherwa** [comment]
Looks good, you might have to change the color layout, but that can be done in another PR

**Review by misherwa — APPROVED** [review]

**Comment by misherwa** [comment]
Hey Daniel, 

I think you  also might want to update your description since the categories or titles like you're "Category" and "Description" aren't bold, and the checklist should be a checklist like this:
image


I recommend going to another PR, like PR #92, clicking on the edit button for their description, copying the format they have, removing their descriptions, and adding yours. You're following the PR format, but it's displayed correctly.

**Comment by thecatfour** [comment]
The only problem that I see with the conversations is the color of the username when trying to create a new conversation. This is what I see when I have my computer set on dark mode. The white on white color is hard to read:

image

Here I highlight the username by selecting it:

image

However, this is what I see when I have my computer on light mode:

image

I can read the username, but everything else is harder to read.

Since my computer is going to be running the server, I could use either mode or just fix the colors on my end. However, it might be a good idea to set up specific colors just in case.

**Review by thecatfour — APPROVED** [review]

**Comment by leed85** [comment]
> The only problem that I see with the conversations is the color of the username when trying to create a new conversation. This is what I see when I have my computer set on dark mode. The white on white color is hard to read:
> 
> image
> 
> Here I highlight the username by selecting it:
> 
> image
> 
> However, this is what I see when I have my computer on light mode:
> 
> image
> 
> I can read the username, but everything else is harder to read.
> 
> Since my computer is going to be running the server, I could use either mode or just fix the colors on my end. However, it might be a good idea to set up specific colors just in case.

I just hard set background to black

**Comment by thecatfour** [comment]
It works as intended now.

**Pull request merged**
