### PR TITLE
Private Messaging Backend

### PR DESCRIPTION
**Pull request by misherwa**
### Category
- [x] **Feature**
- [ ] **Bug Fix**
- [ ] **Testing**
- [ ] **Documentation**
- [ ] **Other**

### Domain
- [ ] **Frontend**
- [x] **Backend**
- [ ] **Both**

### Description
Creating the backend for private messaging (DMs). This is for a new feature where users can privately message outside of Hubs. I want to ensure that a conversation can only be started by the user or another user. The conversation should still be saved after both users leave or close, so when the same two users return, their messages will be saved.  For now, I'll have it so that messages can only be deleted instead of the entire conversation.

### Related Issue(s)
#56, #76  

### New Additions
Used "startapp" to set up the Private_Messaging folder and added files;

- __init__.py
- admin.py
- apps.py
- serializers.py
- models.py
- urls.py
- views.py
- test.py

### Modifications
Needed to modify the settings.py and urls.py in the Rebel_hubs folder so that Private_Messaging can be used and accessed.

### New Dependencies
Using Asynchronous support from Django, so no other things need to be downloaded.

I've got this from: https://docs.djangoproject.com/en/5.0/topics/async/ 

### Visuals
As of now, I am trying to follow this diagram for the backend:

q

### Architecture of Your Changes
This is a feature that will be added to a user's profile page.

### Usage and Integration
Private Messaging should be mainly integrated with a user's profile page. Specifically, to use private messaging, you could click on a user's profile from places such as Posts or Comments. Then you will be brought to another user's profile page, where then you can click a messages icon and you will be brought to Private Messaging with a conversation room with the other user. You can also access Private Messaging through the sidebar. But for now, you must find or search the user to message them. Making this similar to how it is done on Instagram. 

When a user clicks on the chat message, it automatically checks if a conversation was already made. If so, then the previous conversation gets pulled up. Otherwise, a new conversation is made.

### Testing
Testing will be done through test cases in the test.py file. Commands to run the test will be given. I will add a few test cases since changes might be made to the backend based on frontend.

Commennad done in backend folder: 
- python manage.py test Private_Messaging
- coverage run --source=Private_Messaging manage.py test Private_Messaging (targets only the test.py file in Private_Messaging folder)
- coverage report -m 

### Mentions
@thecatfour, @imawful 

Note: This PR is connected to PR #76 which ended up being closed. Any comments or interactions from there are going to be applied to this PR.

### CODE REVIEW

**Comment by misherwa** [comment]
https://github.com/UNLV-CS472-672/2024-F-GROUP3-RebelHub/pull/76#issuecomment-2499341187 

https://github.com/UNLV-CS472-672/2024-F-GROUP3-RebelHub/pull/76#issuecomment-2504655101

I added two test cases. One checks if a message is being sent to no user (error), and the other is adding a message to the conversation.

**Review by thecatfour — APPROVED** [review]
Since my main issues were fixed in the move from PR #76 to #81 (this one), I believe that this is ready to be merged. We could use more tests in the future, so we should keep that in mind.

**Comment by misherwa** [comment]
> Since my main issues were fixed in the move from PR #76 to #81 (this one), I believe that this is ready to be merged. We could use more tests in the future, so we should keep that in mind.

Sure, I'll try to get to more test cases after the frontend part of Private Messaging looks good

**Review by leed85 — APPROVED** [review]

**Comment by leed85** [comment]
It looks good, once we start the frontend we can go over if any other features are needed

**Pull request merged**
