### PR TITLE
Searchbar

### PR DESCRIPTION
**Pull request by courtmcgee2197**
*Please complete the checklist so the group can quickly understand your PR.*

### Category
- [x] **Feature**
- [ ] **Bug Fix**
- [ ] **Testing**
- [ ] **Documentation**
- [ ] **Other**

### Domain
- [x] **Frontend**
- [ ] **Backend**
- [ ] **Both**

### Description
I added a searchbar component that allows you to search based on hubs or clubs

### Related Issue(s)
#50 

### New Additions
frontend/src/components/navbar/RebelHubNavBar.js-Added searchbar component and results
frontend/src/components/searchbar/searchbar.css-Styling for the searchbar
frontend/src/components/searchbar/searchbar.js-This contains the code that makes the api call based on user input
frontend/src/components/searchbar/searchresult.css-This will handle the routing for the results but currently just displays a message to console
frontend/src/components/searchbar/searchresults.css-Styling for the results list
frontend/src/components/searchbar/searchresults.js-This populates the search result list from

### Modifications
List any files modified in this PR with a quick explanation of the purpose behind each change. Ensure this aligns with the "Files changed" tab.
frontend/src/app/page.js-Minor modification for the protected route 

### New Dependencies
N/A

### Visuals
Include any screenshots or diagrams that clarify your additions or changes. Feel free to add visuals throughout the PR where needed.

image

image

### Usage and Integration
Any page that needs a search bar for searching hubs or clubs can use this component however my styling was based on the home page 

### Testing
Entered a couple different hubs into the database and tested if I could search them on the search bar

### CODE REVIEW

**Comment by thecatfour** [comment]
First, I think you should merge this branch to be up-to-date with the master branch. Besides that, I have a couple of changes that I would like to see.

### Change 1
Instead of making an API call each type a key is pressed in the search bar, I think it would be a better idea to use useEffect to store the hubs in a useState. You can then use this variable to filter hubs for the results function. Here is an image of the changes that I would make to use a hook instead of API calls:

image

### Change 2
Instead of alerting the user about the hub being clicked, I think it would be better to redirect the user to the hub that they clicked. I added the following code to searchresult.js and searchresults.js to get it to redirect the user:

image

image

Note that I tested the code in Change 2 of the base of my changes in Change 1, so they may not work without each other.

### Conclusion
After implementing the changes that I suggest, I think this PR will be ready to merge. My suggestions are slight changes to the existing code, so I don't think they will interfere with  the existing code.

**Review by leed85 — APPROVED** [review]

**Review by leed85 — APPROVED** [review]
I think this is good for now, maybe in the future once its populated and more developed, we can also show like the hubs icon next to the hub name like reddit does

**Comment by courtmcgee2197** [comment]
I incorporated the changes for the redirect logic however did not use the code for using the use effect hook.

**Comment by misherwa** [comment]
Looks good to merge

**Review by misherwa — APPROVED** [review]

**Pull request merged**
